version: "3.8"
 
services:
  postgres:
    container_name: oc_wildlands_db
    image: postgres:16
    environment:
      POSTGRES_USER: ofca.dev
      POSTGRES_PASSWORD: ofca.dev.pw
      POSTGRES_DB: postgres
    volumes:
      - ./.data/pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keystone:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"