version: "3.8"
 
services:
  postgres:
    container_name: oc-wildland-postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oc_wildland
    volumes:
      - ./.data/pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  keystone:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
